### ISSUE TITLE
Editing Card bug

### ISSUE THREAD

**Issue by sives** [teamstudio/xcontrols-domino#287]
On my iPad with Unplugged (running iOS 8.1.1), the Editing Card doesn't let you edit text

**Comment by whitemx** [comment]
This is working OK for me now.

**Comment by sives** [comment]
It's working for me too, however on the PC browser the Editing Card outline appearance is different to other Cards (possible style glitch)

**Comment by whitemx** [comment]
The Rich Text Editor would never normally show up in that position, you would normally have it inside a dialog. When we had this before, you asked me to change the layout to how it is currently displayed.

**Comment by whitemx** [comment]
The alternative would be to revert to something like this:
![screen shot 2015-01-20 at 11 50 44](https://cloud.githubusercontent.com/assets/856638/5816657/9eda0aa6-a09a-11e4-8b52-b2f51d179d01.png)

**Comment by sives** [comment]
This looks fine - let's go with it

**Comment by edm00se** [comment]
I'm still experiencing this with the current version of the sampler app, in iOS 8.1.2 on an iPad w/ Retina (1st w/ Retina, 4th gen-ish?), (only) in the UnPlugged app.

UnPluged app is current from the App Store, sampler db freshly copied, UnPlugged server is current build (3.1.22.710). Instead of showing the content and letting me edit the RT fields, it shows the "hello world" text. The UnpBootRichTextRead is fine, showing the details entered. When access via mobile Safari (same device) or from desktop, there is no issue and the field lets me edit as expected.
